language: java
jdk:
- oraclejdk8
sudo: false
install: true
script: mvn install
after_success:
  - mvn clean test jacoco:report coveralls:report
  - bash <(curl -s https://codecov.io/bash)
service_name: travis-pro
repo_token: 0iWionxfNqKCCQkZIbnuKJvlukNcVxERl